# Generated by Django 5.1.7 on 2025-05-08 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('membre', 'Membre'), ('gestionnaire', 'Gestionnaire'), ('super_admin', 'Super Administrateur')], default='membre', max_length=20)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(default='Pas de description')),
                ('montant_cotisation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequence_cotisation', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel')], default='mensuel', max_length=20)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tontines_gerees', to='gestion_tontine.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gestion_tontine.membre')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='gestion_tontine.tontine')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='gestion_tontine.membre')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gestion_tontine.tontine')),
            ],
            options={
                'unique_together': {('membre', 'tontine')},
            },
        ),
    ]
