# Generated by Django 5.1.7 on 2025-03-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tontine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('montant_contribue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='gestion_tontine.tontine')),
            ],
        ),
    ]
