# Generated by Django 5.1.7 on 2025-04-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tontine', '0002_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tontine.membre')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tontine.tontine')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tontine.membre')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tontine.tontine')),
            ],
        ),
    ]
